"""chapter 9 asset entity

Adds the ``assets`` table for the CRI asset-criticality lookup (Bible Ch9
step 3). Autogenerated against PostgreSQL and reviewed: one table, two check
constraints (criticality level; a criticality must name its source), one
index. ``criticality`` is nullable because CERT r4.2 has no criticality
source (N9); nothing in the repository fills it from CERT.

Revision ID: 50ba9f46d2ed
Revises: 123b779f392e
Create Date: 2026-09-29 09:00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ba9f46d2ed'
down_revision: Union[str, Sequence[str], None] = '123b779f392e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_key', sa.String(length=64), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=True),
    sa.Column('criticality', sa.String(length=16), nullable=True),
    sa.Column('criticality_source', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.String(length=64), nullable=True),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("criticality IS NULL OR criticality IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_assets_criticality_level')),
    sa.CheckConstraint('criticality IS NULL OR criticality_source IS NOT NULL', name=op.f('ck_assets_criticality_has_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('asset_key', name=op.f('uq_assets_asset_key'))
    )
    op.create_index('ix_assets_owner_user_id', 'assets', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assets_owner_user_id', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
