"""chapter 12 alerts and lineage

Adds the entities Chapter 12 needs (Bible Ch12 step 3, Architecture §20,
§37): ``model_versions``, ``feature_vectors``, ``event_logs``,
``anomaly_scores``, ``risk_scores``, ``alerts``, ``alert_members``,
``alert_reasons`` and ``audit_logs``, plus ``mitre_mappings.alert_id``.

Autogenerated against PostgreSQL and reviewed. Changes made by hand:
``mitre_mappings.alert_id`` is added inside ``batch_alter_table`` so the same
migration also runs on SQLite (the unit tests apply it there); on PostgreSQL
batch mode issues plain ALTER TABLE statements. Check constraints enforce the
rules the chapter depends on: an anomaly score row is always the served
model's (N32), a suppressed alert names the alert it repeats, a deferred
explanation carries its reason (§36), an ATT&CK reason names its rule (N45),
scores stay in range.

Indexes are created with the tables, not after the bulk load as HCEA §12
suggests: the load is bounded (alert member days and the demo sample, D-6),
so index maintenance during it is negligible (deviation C12-6).

Revision ID: 9f3b2c7d4e81
Revises: 7c1e4a9d2b60
Create Date: 2026-10-01 09:00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f3b2c7d4e81'
down_revision: Union[str, Sequence[str], None] = '7c1e4a9d2b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action_target', 'audit_logs', ['action', 'target_id'], unique=False)
    op.create_table('feature_vectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('profile', sa.String(length=16), nullable=False),
    sa.Column('features_fingerprint', sa.String(length=32), nullable=False),
    sa.Column('pipeline_version', sa.String(length=64), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('loaded_for', sa.String(length=16), nullable=False),
    sa.Column('first_alert_run_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_vectors'))
    )
    op.create_index('ix_feature_vectors_user_day', 'feature_vectors', ['user_id', 'activity_date'], unique=False)
    op.create_index('uq_feature_vectors_fp_user_day', 'feature_vectors', ['features_fingerprint', 'user_id', 'activity_date'], unique=True)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=32), nullable=False),
    sa.Column('registry_version', sa.String(length=16), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('run_id', sa.String(length=128), nullable=True),
    sa.Column('profile', sa.String(length=16), nullable=True),
    sa.Column('trained_at', sa.String(length=64), nullable=True),
    sa.Column('split_mode', sa.String(length=16), nullable=True),
    sa.Column('n_input_columns', sa.Integer(), nullable=True),
    sa.Column('artifact_dir', sa.Text(), nullable=True),
    sa.Column('files', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions'))
    )
    op.create_index('ix_model_versions_name_registry', 'model_versions', ['model_name', 'registry_version'], unique=False)
    op.create_index('uq_model_versions_model_version', 'model_versions', ['model_version'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_run_id', sa.String(length=64), nullable=False),
    sa.Column('alert_key', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('first_date', sa.Date(), nullable=False),
    sa.Column('last_date', sa.Date(), nullable=False),
    sa.Column('peak_date', sa.Date(), nullable=False),
    sa.Column('n_days', sa.Integer(), nullable=False),
    sa.Column('peak_anomaly_score', sa.Float(), nullable=False),
    sa.Column('peak_cri_score', sa.Float(), nullable=False),
    sa.Column('max_cri_score', sa.Float(), nullable=False),
    sa.Column('max_severity', sa.String(length=16), nullable=False),
    sa.Column('queue_score', sa.Float(), nullable=False),
    sa.Column('ordering', sa.String(length=32), nullable=False),
    sa.Column('triggers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('techniques', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('signature', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('top_feature', sa.String(length=128), nullable=True),
    sa.Column('model_split', sa.String(length=16), nullable=False),
    sa.Column('explanation_status', sa.String(length=32), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('policy_hash', sa.String(length=16), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('batch_run_id', sa.String(length=64), nullable=False),
    sa.Column('cri_run_id', sa.String(length=96), nullable=False),
    sa.Column('explain_run_id', sa.String(length=64), nullable=False),
    sa.Column('mitre_run_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("explanation_status IN ('complete', 'model_explanation_deferred')", name=op.f('ck_alerts_explanation_status_value')),
    sa.CheckConstraint("max_severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name=op.f('ck_alerts_severity_value')),
    sa.CheckConstraint("status <> 'open' OR duplicate_of_id IS NULL", name=op.f('ck_alerts_open_is_not_a_duplicate')),
    sa.CheckConstraint("status <> 'suppressed' OR duplicate_of_id IS NOT NULL", name=op.f('ck_alerts_suppressed_names_original')),
    sa.CheckConstraint("status IN ('open', 'suppressed')", name=op.f('ck_alerts_status_value')),
    sa.CheckConstraint('first_date <= peak_date AND peak_date <= last_date', name=op.f('ck_alerts_peak_inside_span')),
    sa.CheckConstraint('n_days >= 1', name=op.f('ck_alerts_has_members')),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['alerts.id'], name=op.f('fk_alerts_duplicate_of_id_alerts')),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_alerts_model_version_id_model_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index('ix_alerts_run_status_queue', 'alerts', ['alert_run_id', 'status', 'queue_score'], unique=False)
    op.create_index('ix_alerts_user_first_date', 'alerts', ['user_id', 'first_date'], unique=False)
    op.create_index('uq_alerts_run_key', 'alerts', ['alert_run_id', 'alert_key'], unique=True)
    op.create_table('anomaly_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('feature_vector_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('registry_version', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('model_split', sa.String(length=16), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('batch_run_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role = 'served'", name=op.f('ck_anomaly_scores_served_only')),
    sa.CheckConstraint('anomaly_score >= 0 AND anomaly_score <= 1', name=op.f('ck_anomaly_scores_score_range')),
    sa.ForeignKeyConstraint(['feature_vector_id'], ['feature_vectors.id'], name=op.f('fk_anomaly_scores_feature_vector_id_feature_vectors')),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_anomaly_scores_model_version_id_model_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anomaly_scores'))
    )
    op.create_index('ix_anomaly_scores_user_day', 'anomaly_scores', ['user_id', 'activity_date'], unique=False)
    op.create_index('uq_anomaly_scores_batch_user_day', 'anomaly_scores', ['batch_run_id', 'user_id', 'activity_date'], unique=True)
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('feature_vector_id', sa.Integer(), nullable=True),
    sa.Column('loaded_for', sa.String(length=16), nullable=False),
    sa.Column('first_alert_run_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('logon', 'device', 'file', 'email', 'http')", name=op.f('ck_event_logs_source_type_value')),
    sa.ForeignKeyConstraint(['feature_vector_id'], ['feature_vectors.id'], name=op.f('fk_event_logs_feature_vector_id_feature_vectors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_logs'))
    )
    op.create_index('ix_event_logs_feature_vector_id', 'event_logs', ['feature_vector_id'], unique=False)
    op.create_index('ix_event_logs_user_day', 'event_logs', ['user_id', 'activity_date'], unique=False)
    op.create_index('uq_event_logs_source_event', 'event_logs', ['source_type', 'event_id'], unique=True)
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anomaly_score_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('cri_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('components', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('points', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('missing_components', sa.Text(), nullable=True),
    sa.Column('historical_top_feature', sa.String(length=128), nullable=True),
    sa.Column('peer_top_feature', sa.String(length=128), nullable=True),
    sa.Column('ldap_role', sa.String(length=128), nullable=True),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('cri_version', sa.String(length=32), nullable=False),
    sa.Column('cri_config_hash', sa.String(length=32), nullable=False),
    sa.Column('cri_variant', sa.String(length=32), nullable=False),
    sa.Column('calibration_id', sa.String(length=64), nullable=False),
    sa.Column('formula_hash', sa.String(length=32), nullable=True),
    sa.Column('cri_run_id', sa.String(length=96), nullable=False),
    sa.Column('mitre_run_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name=op.f('ck_risk_scores_severity_value')),
    sa.CheckConstraint('anomaly_score >= 0 AND anomaly_score <= 1', name=op.f('ck_risk_scores_anomaly_range')),
    sa.CheckConstraint('cri_score >= 0 AND cri_score <= 100', name=op.f('ck_risk_scores_cri_range')),
    sa.ForeignKeyConstraint(['anomaly_score_id'], ['anomaly_scores.id'], name=op.f('fk_risk_scores_anomaly_score_id_anomaly_scores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_scores'))
    )
    op.create_index('ix_risk_scores_anomaly_score_id', 'risk_scores', ['anomaly_score_id'], unique=False)
    op.create_index('ix_risk_scores_user_day', 'risk_scores', ['user_id', 'activity_date'], unique=False)
    op.create_index('uq_risk_scores_run_user_day', 'risk_scores', ['cri_run_id', 'user_id', 'activity_date'], unique=True)
    op.create_table('alert_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('risk_score_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('is_peak', sa.Boolean(), nullable=False),
    sa.Column('by_band', sa.Boolean(), nullable=False),
    sa.Column('by_top_k', sa.Boolean(), nullable=False),
    sa.Column('explanation_status', sa.String(length=32), nullable=False),
    sa.Column('explanation_reason', sa.Text(), nullable=True),
    sa.Column('explanation_text', sa.Text(), nullable=False),
    sa.Column('explanation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('kernel_top5_overlap', sa.Float(), nullable=True),
    sa.Column('kernel_deletion_beats_random', sa.Boolean(), nullable=True),
    sa.Column('explain_run_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("explanation_status <> 'model_explanation_deferred' OR explanation_reason IS NOT NULL", name=op.f('ck_alert_members_deferred_has_reason')),
    sa.CheckConstraint("explanation_status IN ('complete', 'model_explanation_deferred')", name=op.f('ck_alert_members_explanation_status_value')),
    sa.CheckConstraint('by_band OR by_top_k', name=op.f('ck_alert_members_triggered')),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_alert_members_alert_id_alerts')),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], name=op.f('fk_alert_members_risk_score_id_risk_scores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_members'))
    )
    op.create_index('ix_alert_members_risk_score_id', 'alert_members', ['risk_score_id'], unique=False)
    op.create_index('ix_alert_members_user_day', 'alert_members', ['user_id', 'activity_date'], unique=False)
    op.create_index('uq_alert_members_alert_day', 'alert_members', ['alert_id', 'activity_date'], unique=True)
    op.create_table('alert_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('section', sa.String(length=16), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('explain_run_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("section <> 'cri' OR weight IS NOT NULL", name=op.f('ck_alert_reasons_cri_has_points')),
    sa.CheckConstraint("section <> 'mitre' OR rule_id IS NOT NULL", name=op.f('ck_alert_reasons_mitre_names_rule')),
    sa.CheckConstraint("section IN ('model', 'model_lowering', 'cri', 'mitre')", name=op.f('ck_alert_reasons_section_value')),
    sa.CheckConstraint("section NOT IN ('model', 'model_lowering') OR weight IS NOT NULL", name=op.f('ck_alert_reasons_model_has_contribution')),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_alert_reasons_alert_id_alerts')),
    sa.ForeignKeyConstraint(['member_id'], ['alert_members.id'], name=op.f('fk_alert_reasons_member_id_alert_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_reasons'))
    )
    op.create_index('ix_alert_reasons_alert_id', 'alert_reasons', ['alert_id'], unique=False)
    op.create_index('ix_alert_reasons_member_id', 'alert_reasons', ['member_id'], unique=False)
    with op.batch_alter_table('mitre_mappings') as batch:
        batch.add_column(sa.Column('alert_id', sa.Integer(), nullable=True))
        batch.create_index('ix_mitre_mappings_alert_id', ['alert_id'], unique=False)
        batch.create_foreign_key(op.f('fk_mitre_mappings_alert_id_alerts'), 'alerts', ['alert_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('mitre_mappings') as batch:
        batch.drop_constraint(op.f('fk_mitre_mappings_alert_id_alerts'), type_='foreignkey')
        batch.drop_index('ix_mitre_mappings_alert_id')
        batch.drop_column('alert_id')
    op.drop_index('ix_alert_reasons_member_id', table_name='alert_reasons')
    op.drop_index('ix_alert_reasons_alert_id', table_name='alert_reasons')
    op.drop_table('alert_reasons')
    op.drop_index('uq_alert_members_alert_day', table_name='alert_members')
    op.drop_index('ix_alert_members_user_day', table_name='alert_members')
    op.drop_index('ix_alert_members_risk_score_id', table_name='alert_members')
    op.drop_table('alert_members')
    op.drop_index('uq_risk_scores_run_user_day', table_name='risk_scores')
    op.drop_index('ix_risk_scores_user_day', table_name='risk_scores')
    op.drop_index('ix_risk_scores_anomaly_score_id', table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index('uq_event_logs_source_event', table_name='event_logs')
    op.drop_index('ix_event_logs_user_day', table_name='event_logs')
    op.drop_index('ix_event_logs_feature_vector_id', table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index('uq_anomaly_scores_batch_user_day', table_name='anomaly_scores')
    op.drop_index('ix_anomaly_scores_user_day', table_name='anomaly_scores')
    op.drop_table('anomaly_scores')
    op.drop_index('uq_alerts_run_key', table_name='alerts')
    op.drop_index('ix_alerts_user_first_date', table_name='alerts')
    op.drop_index('ix_alerts_run_status_queue', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('uq_model_versions_model_version', table_name='model_versions')
    op.drop_index('ix_model_versions_name_registry', table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index('uq_feature_vectors_fp_user_day', table_name='feature_vectors')
    op.drop_index('ix_feature_vectors_user_day', table_name='feature_vectors')
    op.drop_table('feature_vectors')
    op.drop_index('ix_audit_logs_action_target', table_name='audit_logs')
    op.drop_table('audit_logs')
