"""Run everything Chapter 8 needs on the real data, in order, and stop at the first failure.

Usage, from backend/ (the script loads the repository's .env for any variable
not already set):

    python ../scripts/signoff_chapter8.py              # run / resume the sign-off
    python ../scripts/signoff_chapter8.py --finalize   # after reviewing the audit: raise the status

Sign-off sequence (CARRY_FORWARD N27, docs/chapters/chapter_8_scoring.md "How to run"):

    0  preflight   env, feature files, labels, split files, Chapter 6/7 reference
                   runs and their score files, TabNet registry versions (sha256)
    1  tests       the full pytest suite (skip with --skip-tests)
    2  candidates  behaviour-only XGBoost at mid/user, mid/time, full/user; the
                   time split uses the dates of the Chapter 7 mid/time run, so
                   both models are scored on the same rows
    3  verify      each candidate: verify_chapter8.py --permutation-test --no-decision
    4  decide      python -m app.scoring.select (validation only)
    5  test        python -m app.scoring.select --report-test (once)
    6  batch       python -m app.scoring.batch --profile full --with-shadow
    7  verify      verify_chapter8.py on decision + served model + batch
    8  health      the FastAPI app starts and /health reports the decided model
    9  record      experiments/chapter8_reference_runs.json and an audit draft
                   (docs/audits/chapter_8_audit.md) written from the output files

Every heavy step runs in its own process, one at a time (HCEA §16), with its
output in experiments/results/chapter8/signoff_logs/. Progress is kept in
experiments/results/chapter8/signoff_state.json, so a re-run skips what is
already done: a candidate that is registered and verified, the decision, the
test readout, a batch made with the current decision. Nothing that already
exists is overwritten, and test is never read twice.

The audit draft contains only numbers copied from the run outputs. Each WARN
the verifier printed becomes a "TO EXPLAIN" line that a person must replace
with the reason it is acceptable. ``--finalize`` refuses while any remain.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
BACKEND = REPO / "backend"
KEYS = ("mid/user", "mid/time", "full/user")
TO_EXPLAIN = "TO EXPLAIN"
DRAFT_MARK = "<!-- generated by scripts/signoff_chapter8.py from run outputs -->"


class SignoffError(RuntimeError):
    """A step failed; the sign-off stops here."""


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def load_dotenv(path: Path) -> list[str]:
    """Set KEY=VALUE pairs from ``path`` that are not already in the environment."""
    loaded = []
    if not path.exists():
        return loaded
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key, value = key.strip(), value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value
            loaded.append(key)
    return loaded


def read_json(path: Path) -> dict:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")
    tmp.replace(path)


def sha256(path: Path) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def runlog_lines(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [json.loads(x) for x in path.read_text(encoding="utf-8").splitlines() if x.strip()]


def fmt(v, nd: int = 3) -> str:
    if v is None:
        return "n/a"
    return f"{v:.{nd}f}" if isinstance(v, float) else str(v)


class Ctx:
    def __init__(self, args: argparse.Namespace) -> None:
        self.args = args
        exp = Path(args.experiments_dir)
        self.exp = exp
        self.results = exp / "results" / "chapter8"
        self.logs = self.results / "signoff_logs"
        self.state_path = self.results / "signoff_state.json"
        self.decision = exp / "chapter8_serving_decision.json"
        self.readout = exp / "chapter8_test_readout.json"
        self.reference = exp / "chapter8_reference_runs.json"
        self.ch6_refs = exp / "chapter6_reference_runs.json"
        self.ch7_refs = exp / "chapter7_reference_runs.json"
        self.splits = exp / "splits"
        self.docs = Path(args.docs_root)
        self.audit = self.docs / "docs" / "audits" / "chapter_8_audit.md"
        self.processed = Path(args.processed_dir) if args.processed_dir else None
        self.models = Path(args.models_dir)
        self.runlog = Path(os.environ.get("CIRA_RUNLOG", str(exp / "runlog.jsonl")))
        self.state = read_json(self.state_path) if self.state_path.exists() else {}
        self.state.setdefault("candidates", {})
        self.state.setdefault("candidate_verification", {})

    def save(self) -> None:
        self.state["updated_at"] = now()
        write_json(self.state_path, self.state)

    def env(self) -> dict:
        env = dict(os.environ)
        env["MODEL_PATH"] = str(self.models)
        env["CIRA_SERVING_DECISION"] = str(self.decision)
        env["CERT_PROCESSED_DIR"] = str(self.processed)
        env["CIRA_RUNLOG"] = str(self.runlog)
        env.pop("CIRA_SERVED_MODEL", None)      # the sign-off always serves the recorded decision
        env.pop("CIRA_SHADOW_MODEL", None)
        env["PYTHONPATH"] = str(BACKEND) + os.pathsep + env.get("PYTHONPATH", "")
        env["PYTHONIOENCODING"] = "utf-8"       # Windows pipes default to cp1252; the logs are read as UTF-8
        return env

    def run(self, name: str, argv: list[str], *, cwd: Path = BACKEND) -> tuple[int, str]:
        """Run one step in its own process, echoing and logging its output."""
        self.logs.mkdir(parents=True, exist_ok=True)
        log = self.logs / f"{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}_{name}.log"
        print(f"\n>>> {name}: {' '.join(argv)}", flush=True)
        lines = []
        with log.open("w", encoding="utf-8") as fh:
            proc = subprocess.Popen([sys.executable, *argv], cwd=cwd, env=self.env(), stdout=subprocess.PIPE,
                                    stderr=subprocess.STDOUT, text=True, encoding="utf-8", errors="replace")
            for line in proc.stdout:
                fh.write(line)
                lines.append(line)
                if not self.args.quiet:
                    sys.stdout.write(line)
            code = proc.wait()
        print(f"<<< {name}: exit {code}  (log: {log})", flush=True)
        return code, "".join(lines)


def verifier_lines(output: str, status: str) -> list[str]:
    return [line.strip() for line in output.splitlines() if line.strip().startswith(status + " ")]


def verifier_counts(output: str) -> dict:
    for line in reversed(output.splitlines()):
        if " PASS, " in line and " FAIL" in line:
            parts = line.split("->")[0].replace(",", "").split()
            return {parts[i + 1]: int(parts[i]) for i in range(0, 6, 2)}
    return {}


# ---------------------------------------------------------------------------
# steps
# ---------------------------------------------------------------------------

def preflight(ctx: Ctx) -> dict:
    print("\n=== 0 preflight ===")
    problems = []
    if ctx.processed is None:
        raise SignoffError("CERT_PROCESSED_DIR is not set (in the environment or the repository .env)")
    for profile in ("mid", "full"):
        f = ctx.processed / "features" / f"user_day_{profile}.parquet"
        if not f.exists():
            problems.append(f"missing {f}")
        s = ctx.splits / f"user_split_{profile}_seed{ctx.args.seed}.json"
        if not s.exists():
            problems.append(f"missing split file {s}")
    for name in ("insider_user_days.parquet", "account_user_days.parquet"):
        if not (ctx.processed / "labels" / name).exists():
            problems.append(f"missing label table {name}; run scripts/build_labels.py")
    for ref in (ctx.ch6_refs, ctx.ch7_refs):
        if not ref.exists():
            problems.append(f"missing {ref}")
    if problems:
        raise SignoffError("preflight: " + "; ".join(problems))

    sys.path.insert(0, str(BACKEND))
    from app.tabnet.model_registry import ModelRegistry, RegistryError

    ch6, ch7 = read_json(ctx.ch6_refs), read_json(ctx.ch7_refs)
    tabnet = {}
    reg = ModelRegistry(ctx.models, "tabnet")
    for key in KEYS:
        ref = (ch7.get("runs") or {}).get(key)
        if not ref:
            problems.append(f"no Chapter 7 reference run for {key}")
            continue
        try:
            entry = reg.resolve(ref["registry_version"])
        except RegistryError as exc:
            problems.append(f"TabNet {key} {ref['registry_version']}: {exc} (MODEL_PATH={ctx.models})")
            continue
        bad = reg.verify(entry)
        if bad:
            problems.append(f"TabNet {key} {ref['registry_version']} fails sha256: {bad}")
        if entry.get("run_id") != ref["run_id"]:
            problems.append(f"TabNet {key}: registry {ref['registry_version']} holds run {entry.get('run_id')}, reference says {ref['run_id']}")
        score = ctx.processed / "scores" / "chapter7" / ref["run_id"] / "tabnet.parquet"
        if not score.exists():
            problems.append(f"missing TabNet score file {score}")
        tabnet[key] = {**ref, "split": entry.get("split") or {}}
        g6 = (ch6.get("runs") or {}).get(key, {}).get("gbdt")
        if not g6 or not (ctx.processed / "scores" / "chapter6" / g6 / "gbdt.parquet").exists():
            problems.append(f"Chapter 6 XGBoost reference score file for {key} not found")
    if problems:
        raise SignoffError("preflight: " + "; ".join(problems))
    print(f"  processed: {ctx.processed}\n  models:    {ctx.models}\n  runlog:    {ctx.runlog}")
    print("  Chapter 7 reference TabNet: " + ", ".join(f"{k} {v['registry_version']}" for k, v in tabnet.items()))
    if os.environ.get("CIRA_SERVED_MODEL"):
        print("  NOTE: CIRA_SERVED_MODEL is set; the sign-off ignores it and serves the recorded decision.")
    print("  preflight OK")
    return tabnet


def tests(ctx: Ctx) -> None:
    print("\n=== 1 tests ===")
    if ctx.args.skip_tests:
        print("  skipped (--skip-tests)")
        return
    code, out = ctx.run("pytest", ["-m", "pytest", "-q"], cwd=REPO)
    tail = [line for line in out.splitlines() if " passed" in line or " failed" in line or " error" in line]
    ctx.state["tests"] = {"exit": code, "summary": tail[-1] if tail else None, "at": now()}
    ctx.save()
    if code != 0:
        raise SignoffError("the test suite is not green; fix it before any real run")


def candidates(ctx: Ctx, tabnet: dict) -> dict:
    print("\n=== 2 candidates ===")
    sys.path.insert(0, str(BACKEND))
    from app.tabnet.model_registry import ModelRegistry, RegistryError

    reg = ModelRegistry(ctx.models, "gbdt")
    runs: dict[str, str] = {}
    if ctx.decision.exists():                      # the decision names its candidates; they are final
        decided = read_json(ctx.decision)["candidates"]["gbdt"]
        runs = {k: v["run_id"] for k, v in decided.items()}
        print("  decision exists: candidates are the ones it names")
    for key in KEYS:
        if key in runs:
            continue
        known = ctx.state["candidates"].get(key)
        if known:
            try:
                reg.resolve(known)
                runs[key] = known
                print(f"  {key}: already trained ({known})")
                continue
            except RegistryError:
                print(f"  {key}: recorded run {known} is not registered; training again")
        profile, split = key.split("/")
        argv = ["-m", "app.scoring.gbdt_candidate", "--processed-dir", str(ctx.processed), "--profile", profile,
                "--split", split, "--seed", str(ctx.args.seed), "--splits-dir", str(ctx.splits),
                "--results-dir", str(ctx.results), "--models-dir", str(ctx.models)]
        if split == "time":
            s = tabnet[key]["split"]
            if not (s.get("validation_start") and s.get("test_start")):
                raise SignoffError(f"TabNet {key} registry entry has no time-split dates")
            argv += ["--time-validation-start", s["validation_start"], "--time-test-start", s["test_start"]]
        before = {r.get("run_id") for r in runlog_lines(ctx.runlog) if r.get("stage") == "chapter8_gbdt_candidate"}
        code, _ = ctx.run(f"candidate_{profile}_{split}", argv)
        new = [r for r in runlog_lines(ctx.runlog) if r.get("stage") == "chapter8_gbdt_candidate"
               and r.get("run_id") not in before and r.get("profile") == profile and r.get("split_mode") == split]
        if code != 0 or len(new) != 1 or not new[0].get("registry_version"):
            raise SignoffError(f"candidate {key} did not finish with one registered run (exit {code})")
        runs[key] = new[0]["run_id"]
        ctx.state["candidates"][key] = runs[key]
        ctx.save()
    return runs


def verify_candidates(ctx: Ctx, runs: dict) -> None:
    print("\n=== 3 verify candidates ===")
    for key in KEYS:
        run_id = runs[key]
        done = ctx.state["candidate_verification"].get(key) or {}
        if done.get("run_id") == run_id and done.get("counts", {}).get("FAIL") == 0 and done.get("permutation") == (not ctx.args.skip_permutation):
            print(f"  {key}: already verified ({done['counts']})")
            continue
        profile = key.split("/")[0]
        argv = [str(REPO / "scripts" / "verify_chapter8.py"), "--processed-dir", str(ctx.processed), "--profile", profile,
                "--candidate-run-id", run_id, "--no-decision", "--results-dir", str(ctx.results),
                "--splits-dir", str(ctx.splits), "--models-dir", str(ctx.models), "--ch6-references", str(ctx.ch6_refs),
                "--ch7-references", str(ctx.ch7_refs)]
        if not ctx.args.skip_permutation:
            argv.append("--permutation-test")
        code, out = ctx.run(f"verify_candidate_{key.replace('/', '_')}", argv)
        record = {"run_id": run_id, "exit": code, "counts": verifier_counts(out), "warn": verifier_lines(out, "WARN"),
                  "fail": verifier_lines(out, "FAIL"), "leakage": [x for x in out.splitlines() if " leakage " in x],
                  "permutation": not ctx.args.skip_permutation, "at": now()}
        ctx.state["candidate_verification"][key] = record
        ctx.save()
        if code != 0:
            raise SignoffError(f"candidate {key} ({run_id}) failed verification:\n  " + "\n  ".join(record["fail"]))


def decide(ctx: Ctx, runs: dict) -> None:
    print("\n=== 4 decision (validation only) ===")
    if ctx.decision.exists():
        print(f"  exists: {ctx.decision} (a decision is made once)")
        return
    argv = ["-m", "app.scoring.select", "--processed-dir", str(ctx.processed), "--decision-path", str(ctx.decision),
            "--test-readout-path", str(ctx.readout), "--ch7-references", str(ctx.ch7_refs),
            "--ch6-references", str(ctx.ch6_refs), "--models-dir", str(ctx.models), "--seed", str(ctx.args.seed)]
    for key in KEYS:
        argv += ["--gbdt", f"{key}={runs[key]}"]
    code, _ = ctx.run("select", argv)
    if code != 0 or not ctx.decision.exists():
        raise SignoffError(f"the serving decision was not written (exit {code})")


def test_readout(ctx: Ctx) -> None:
    print("\n=== 5 test readout (once) ===")
    if ctx.readout.exists():
        print(f"  exists: {ctx.readout} (test is read once)")
        return
    argv = ["-m", "app.scoring.select", "--report-test", "--processed-dir", str(ctx.processed),
            "--decision-path", str(ctx.decision), "--test-readout-path", str(ctx.readout),
            "--ch7-references", str(ctx.ch7_refs), "--ch6-references", str(ctx.ch6_refs), "--models-dir", str(ctx.models),
            "--seed", str(ctx.args.seed)]
    code, _ = ctx.run("report_test", argv)
    if code != 0 or not ctx.readout.exists():
        raise SignoffError(f"the test readout was not written (exit {code})")


def batch(ctx: Ctx) -> str:
    print("\n=== 6 batch scoring ===")
    current = sha256(ctx.decision)
    known = ctx.state.get("batch_run_id")
    if known:
        meta = ctx.processed / "scores" / "chapter8" / known / "batch_meta.json"
        if meta.exists() and read_json(meta).get("decision_sha256") == current:
            print(f"  already scored with the current decision ({known})")
            return known
    before = {r.get("batch_run_id") for r in runlog_lines(ctx.runlog) if r.get("stage") == "chapter8_batch_scoring"}
    code, _ = ctx.run("batch", ["-m", "app.scoring.batch", "--processed-dir", str(ctx.processed), "--profile", "full",
                                "--with-shadow", "--splits-dir", str(ctx.splits)])
    new = [r for r in runlog_lines(ctx.runlog) if r.get("stage") == "chapter8_batch_scoring" and r.get("batch_run_id") not in before]
    if code != 0 or len(new) != 1:
        raise SignoffError(f"batch scoring did not finish (exit {code})")
    ctx.state["batch_run_id"] = new[0]["batch_run_id"]
    ctx.save()
    return ctx.state["batch_run_id"]


def final_verify(ctx: Ctx, runs: dict, batch_run_id: str) -> dict:
    print("\n=== 7 verify decision, served model, batch ===")
    argv = [str(REPO / "scripts" / "verify_chapter8.py"), "--processed-dir", str(ctx.processed), "--profile", "full",
            "--candidate-run-id", runs["full/user"], "--batch-run-id", batch_run_id, "--decision-path", str(ctx.decision),
            "--test-readout-path", str(ctx.readout), "--results-dir", str(ctx.results), "--splits-dir", str(ctx.splits),
            "--models-dir", str(ctx.models), "--ch6-references", str(ctx.ch6_refs), "--ch7-references", str(ctx.ch7_refs)]
    code, out = ctx.run("verify_final", argv)
    record = {"exit": code, "counts": verifier_counts(out), "warn": verifier_lines(out, "WARN"), "fail": verifier_lines(out, "FAIL"),
              "detail": [x.strip() for x in out.splitlines() if x.strip()[:4] in ("PASS", "WARN", "FAIL")], "at": now()}
    ctx.state["final_verification"] = record
    ctx.save()
    if code != 0:
        raise SignoffError("final verification failed:\n  " + "\n  ".join(record["fail"]))
    return record


HEALTH_CODE = r"""
import json
from fastapi.testclient import TestClient
from app.main import app
with TestClient(app) as client:
    r = client.get("/health")
print("HEALTH_JSON=" + json.dumps({"code": r.status_code, "body": r.json()}))
"""


def health(ctx: Ctx) -> dict:
    print("\n=== 8 API startup and /health ===")
    code, out = ctx.run("health", ["-c", HEALTH_CODE])
    line = next((x for x in out.splitlines() if x.startswith("HEALTH_JSON=")), None)
    if code != 0 or line is None:
        raise SignoffError(f"the API did not start (exit {code})")
    got = json.loads(line[len("HEALTH_JSON="):])
    body, want = got["body"], read_json(ctx.decision)["outcome"]["served"]
    model = body.get("anomaly_model") or {}
    served = model.get("served") or {}
    ok = (got["code"] == 200 and body.get("status") == "healthy" and model.get("source") == "decision_file"
          and served.get("registry_version") == want["registry_version"] and served.get("model_version") == want["model_version"]
          and served.get("device") == "cpu")
    ctx.state["health"] = {"ok": ok, "status": body.get("status"), "source": model.get("source"),
                           "served": {k: served.get(k) for k in ("model_name", "registry_version", "model_version", "device")},
                           "shadow": [s.get("registry_version") for s in model.get("shadow", [])], "at": now()}
    ctx.save()
    if not ok:
        raise SignoffError(f"/health does not report the decided model on CPU: {json.dumps(ctx.state['health'])}")
    print(f"  /health: healthy, serving {served['model_name']} {served['registry_version']} on CPU")
    return ctx.state["health"]


# ---------------------------------------------------------------------------
# record: reference file and audit draft, from outputs only
# ---------------------------------------------------------------------------

def write_reference(ctx: Ctx, runs: dict, batch_run_id: str) -> None:
    d = read_json(ctx.decision)
    lines = {r["run_id"]: r for r in runlog_lines(ctx.runlog) if r.get("stage") == "chapter8_gbdt_candidate"}
    payload = {
        "description": ("Reported Chapter 8 runs (CARRY_FORWARD N27, N28). The behaviour-only XGBoost candidates, the "
                        "serving decision and the batch run the sign-off verified. Chapter 9 and Chapter 16 use these; "
                        "if anything is re-run for the record, change it here and in docs/audits/chapter_8_audit.md."),
        "gbdt_candidates": {k: {"run_id": runs[k], "registry_version": (lines.get(runs[k]) or {}).get("registry_version"),
                                "model_version": (lines.get(runs[k]) or {}).get("model_version")} for k in KEYS},
        "decision": {"file": "experiments/chapter8_serving_decision.json", "sha256": sha256(ctx.decision),
                     "rule": d["rule"]["version"], "served": d["outcome"]["served"], "shadow": d["outcome"]["shadow"],
                     "deviation": d["outcome"]["deviation"]},
        "test_readout": {"file": "experiments/chapter8_test_readout.json", "sha256": sha256(ctx.readout)},
        "batch_run_id": batch_run_id,
        "batch_output": "<CERT_PROCESSED_DIR>/scores/chapter8/<batch_run_id>/anomaly_scores.parquet",
    }
    write_json(ctx.reference, payload)
    print(f"  written: {ctx.reference}")


def _model_table(ev: dict, labels=("tabnet", "gbdt", "gbdt_ch6_all_feat")) -> list[str]:
    out = ["| Model | PR-AUC | ROC-AUC (secondary) | Recall@1 | Caught@1 | Days at top-1 by scenario | Insiders caught at top-1 by scenario |",
           "|---|---|---|---|---|---|---|"]
    names = {"tabnet": "TabNet (Ch7 reference)", "gbdt": "XGBoost, behaviour-only (Ch8)", "gbdt_ch6_all_feat": "XGBoost, all features (Ch6 reference)"}
    for m in labels:
        e = ev["models"].get(m)
        if not e:
            continue
        rs = ", ".join(f"s{s} {v}" for s, v in e.get("recall_by_scenario_at_1", {}).items())
        cs = ", ".join(f"s{s} {v}" for s, v in e.get("caught_by_scenario_at_1", {}).items())
        out.append(f"| {names[m]} | {fmt(e['pr_auc'])} | {fmt(e['roc_auc_secondary'])} | {fmt(e['recall_at_1'])} | "
                   f"{e['insiders_caught_at_1']} | {rs} | {cs} |")
    return out


def audit_text(ctx: Ctx, runs: dict, batch_run_id: str) -> str:
    d, r = read_json(ctx.decision), read_json(ctx.readout)
    st = ctx.state
    meta = read_json(ctx.processed / "scores" / "chapter8" / batch_run_id / "batch_meta.json")
    cand_lines = {x["run_id"]: x for x in runlog_lines(ctx.runlog) if x.get("stage") == "chapter8_gbdt_candidate"}
    o = d["outcome"]
    served, shadow = o["served"], o["shadow"]
    L = [DRAFT_MARK, "", f"# Chapter 8 audit ({datetime.now(timezone.utc):%d %B %Y})", "",
         "Scope: Chapter 8 (anomaly scoring and serving), checked against the Bible Chapter 8 acceptance",
         "list, HCEA v1.0 §8 and CARRY_FORWARD N1-N32.",
         "Evidence: `experiments/runlog.jsonl`, `experiments/chapter8_serving_decision.json`,",
         "`experiments/chapter8_test_readout.json`, `experiments/chapter8_reference_runs.json`, and the",
         "`scripts/verify_chapter8.py` output of each run (logs under `experiments/results/chapter8/signoff_logs/`,",
         "gitignored). Every number below is copied from those files by `scripts/signoff_chapter8.py`.", "",
         f"Result: every verification finished with 0 FAIL. The served model is **{served['model_name']} "
         f"{served['registry_version']}** (`{served['model_version']}`), chosen by rule `{d['rule']['version']}` on validation.",
         f"Deviation C8-1: {'applies (XGBoost is served instead of the Bible' + chr(39) + 's TabNet)' if o['deviation'] else 'does not apply (TabNet is served)'}.", "",
         "## Candidate runs (behaviour-only XGBoost)", "",
         "| Profile / split | Run id | Registry | model_version | scale_pos_weight | Best iteration | Fit (s) | Peak RSS (MB) |",
         "|---|---|---|---|---|---|---|---|"]
    for k in KEYS:
        x = cand_lines.get(runs[k], {})
        L.append(f"| {k} | `{runs[k]}` | {x.get('registry_version')} | `{x.get('model_version')}` | {fmt(x.get('effective_positive_weight'))} | "
                 f"{x.get('best_iteration')} | {x.get('wall_seconds_fit')} | {x.get('peak_rss_mb')} |")
    L += ["", "## Verification record", "", "| What | Verifier |", "|---|---|"]
    for k in KEYS:
        v = st["candidate_verification"][k]
        c = v["counts"]
        L.append(f"| candidate {k} (`{v['run_id']}`){' with permutation test' if v.get('permutation') else ''} | "
                 f"{c.get('PASS')} PASS, {c.get('WARN')} WARN, {c.get('FAIL')} FAIL |")
    fv = st["final_verification"]["counts"]
    L.append(f"| decision, served model, batch `{batch_run_id}` | {fv.get('PASS')} PASS, {fv.get('WARN')} WARN, {fv.get('FAIL')} FAIL |")
    L.append(f"| test suite | {(st.get('tests') or {}).get('summary') or 'skipped in this sign-off'} |")
    warns = [(f"candidate {k}", w) for k in KEYS for w in st["candidate_verification"][k]["warn"]] + \
            [("final", w) for w in st["final_verification"]["warn"]]
    L += ["", "WARNs and why they are acceptable:", ""]
    if warns:
        L += [f"- **{where}:** `{w}`  \n  {TO_EXPLAIN}: why this is acceptable." for where, w in warns]
    else:
        L.append("- none.")
    leak = [(k, line.strip()) for k in KEYS for line in st["candidate_verification"][k].get("leakage", [])]
    if leak:
        L += ["", "## Permutation test (C7-8 rule, three shuffles)", ""]
        L += [f"- {k}: `{line}`" for k, line in leak]
    L += ["", "## Serving decision (validation, primary view)", "",
          f"Rule `{d['rule']['version']}`: {d['rule']['text']}", "",
          f"Decided {d['decided_at']}. Served: {served['model_name']} {served['registry_version']}. "
          f"Shadow: {'none' if not shadow else shadow['model_name'] + ' ' + shadow['registry_version']}.", "",
          f"Reason recorded by `select`: {o['reason']}", "",
          f"Difference on {d['rule']['decisive']} (XGBoost minus TabNet): {fmt(o['difference_decisive'])}; "
          + ", ".join(f"{k}: {fmt(v)}" for k, v in (o.get("difference_consistency") or {}).items()) + ".", ""]
    gates = d["gates"]
    L += ["Gates: " + "; ".join(f"{m} " + ("passed" if g["ok"] else "FAILED " + json.dumps(g["checks"])) for m, g in gates.items()) + ".", ""]
    for k, ev in d["evidence"].items():
        L += [f"### {k} validation ({ev['rows']} rows, {ev['positives']} malicious user-days, chance {fmt(ev['chance_pr_auc'], 4)})", ""]
        L += _model_table(ev) + [""]
    L += ["## Test readout (read once, after the decision)", "",
          f"Read {r['read_at']}; decision sha256 at that time `{r['decision_sha256'][:12]}`. "
          f"Harness check: {'every recomputed test PR-AUC matches the logged value' if all(x['match'] for rows in r['harness_check'].values() for x in rows) else 'MISMATCH (see the readout file)'}.", ""]
    for k, ev in r["evidence"].items():
        L += [f"### {k} test ({ev['rows']} rows, {ev['positives']} malicious user-days, chance {fmt(ev['chance_pr_auc'], 4)})", ""]
        L += _model_table(ev) + [""]
    s = meta["summary"]
    L += ["## Batch scoring and serving", "",
          f"Batch `{batch_run_id}`: {s['rows_scored']} user-days scored by {meta['served']['model_name']} "
          f"{meta['served']['registry_version']} on CPU, shadow rows {s['shadow_rows']}, model_split {json.dumps(s['rows_by_model_split'])}. "
          f"Saturated served scores: {s['saturated_served_scores']}. Scoring took {meta['score_seconds']} s; peak RSS {meta['peak_rss_mb']} MB. "
          f"Same feature file as training: {meta['features']['same_matrix_as_training']}.", "",
          f"Served score quantiles: {json.dumps(s['served_score_quantiles'])}. Rows tagged `train` are in-sample (N31).", "",
          f"`/health` on this machine: {st['health']['status']}, source {st['health']['source']}, serving "
          f"{st['health']['served']['model_name']} {st['health']['served']['registry_version']} on {st['health']['served']['device']}.", "",
          "## Notes", "",
          "- Every number comes from one seed per model. Chapter 16 adds seeds and bootstrap intervals (C6-2, C7-7).",
          "- The served model's CRI thresholds are tied to its model_version (N29); explanations come from it (N30).", ""]
    return "\n".join(L)


def record(ctx: Ctx, runs: dict, batch_run_id: str) -> Path:
    print("\n=== 9 record ===")
    write_reference(ctx, runs, batch_run_id)
    text = audit_text(ctx, runs, batch_run_id)
    target = ctx.audit
    if target.exists() and DRAFT_MARK not in target.read_text(encoding="utf-8"):
        target = target.with_name("chapter_8_audit.generated.md")
        print(f"  {ctx.audit} was edited by hand; the fresh draft goes to {target} instead")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")
    print(f"  written: {target}")
    return target


# ---------------------------------------------------------------------------
# finalize: raise the status once a person has reviewed the audit
# ---------------------------------------------------------------------------

def _replace(path: Path, old: str, new: str, what: str, manual: list[str]) -> None:
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    if new in text:
        return
    if old not in text:
        manual.append(f"{path}: {what}")
        return
    path.write_text(text.replace(old, new, 1), encoding="utf-8")
    print(f"  updated {path}: {what}")


def finalize(ctx: Ctx) -> int:
    st = ctx.state
    if not st.get("green"):
        raise SignoffError("the last sign-off run was not green; run the sign-off first")
    if not ctx.audit.exists():
        raise SignoffError(f"{ctx.audit} does not exist")
    text = ctx.audit.read_text(encoding="utf-8")
    if TO_EXPLAIN in text:
        n = text.count(TO_EXPLAIN)
        raise SignoffError(f"{ctx.audit} still has {n} '{TO_EXPLAIN}' line(s); explain every WARN first (N27)")
    if DRAFT_MARK in text:
        ctx.audit.write_text(text.replace(DRAFT_MARK + "\n\n", "").replace(DRAFT_MARK, ""), encoding="utf-8")
    served = read_json(ctx.decision)["outcome"]["served"]
    stamp = datetime.now(timezone.utc).strftime("%d %B %Y")
    manual: list[str] = []
    cf = ctx.docs / "docs" / "CARRY_FORWARD.md"
    _replace(cf, "| N27 Chapter 8 status | 8 (until retired) |", "| N27 Chapter 8 status (RETIRED) | - |", "N27 row retired", manual)
    _replace(cf, "## N27. Chapter 8 is PARTIALLY IMPLEMENTED until real runs exist  (from Chapter 8)\n\n",
             "## N27. Chapter 8 is PARTIALLY IMPLEMENTED until real runs exist  (from Chapter 8)\n\n"
             "RETIRED (chapter 8, runs verified; see `docs/audits/chapter_8_audit.md`).\n\n", "N27 marked RETIRED", manual)
    readme = ctx.docs / "README.md"
    _replace(readme, "| 8 | Anomaly scoring service, served-model decision, batch scoring, API model loading | PARTIALLY IMPLEMENTED; synthetic tests pass, CERT runs pending (N27) |",
             f"| 8 | Anomaly scoring service, served-model decision, batch scoring, API model loading | IMPLEMENTED; serving {served['model_name']} {served['registry_version']} |",
             "status row", manual)
    readme_text = readme.read_text(encoding="utf-8") if readme.exists() else ""
    if "docs/audits/chapter_8_audit.md" not in readme_text:
        _replace(readme, "`docs/audits/chapter_7_audit.md` for the chapter reviews",
                 "`docs/audits/chapter_7_audit.md` and `docs/audits/chapter_8_audit.md` for the chapter reviews", "audit link", manual)
    chap = ctx.docs / "docs" / "chapters" / "chapter_8_scoring.md"
    chap_text = chap.read_text(encoding="utf-8") if chap.exists() else ""
    start = chap_text.find("Status: PARTIALLY IMPLEMENTED")
    end = chap_text.find("\n\n", start)
    if start >= 0 and end > start:
        chap_text = chap_text[:start] + (
            f"Status: IMPLEMENTED ({stamp}). Verified on CERT r4.2 with 0 FAIL; the runs, the decision and\n"
            f"every WARN are in `docs/audits/chapter_8_audit.md`. Served model: {served['model_name']}\n"
            f"{served['registry_version']} (`{served['model_version']}`), recorded in\n"
            "`experiments/chapter8_serving_decision.json`. Reported runs: `experiments/chapter8_reference_runs.json`."
        ) + chap_text[end:]
        section = chap_text.find("Real runs (N27), not yet done:")
        if section >= 0:
            chap_text = chap_text[:section] + chap_text[section:].replace("Real runs (N27), not yet done:", "Real runs (N27):", 1).replace("- [ ] ", "- [x] ")
        chap.write_text(chap_text, encoding="utf-8")
        print(f"  updated {chap}: status IMPLEMENTED, real-run checklist ticked")
    elif "Status: IMPLEMENTED" not in chap_text:
        manual.append(f"{chap}: set the status line to IMPLEMENTED")
    st["finalized_at"] = now()
    ctx.save()
    if manual:
        print("\nEdit these by hand (their text no longer matched):\n  " + "\n  ".join(manual))
    print("\nChapter 8 is signed off. Commit:\n"
          "  git add experiments/chapter8_serving_decision.json experiments/chapter8_test_readout.json "
          "experiments/chapter8_reference_runs.json experiments/runlog.jsonl docs/ README.md\n"
          "  git commit -m \"Chapter 8 sign-off: served-model decision, batch scoring, audit\"")
    return 0


# ---------------------------------------------------------------------------

def parse_args(argv: list[str] | None) -> argparse.Namespace:
    load_dotenv(REPO / ".env")
    p = argparse.ArgumentParser(description="CIRA Chapter 8 sign-off")
    p.add_argument("--finalize", action="store_true", help="after reviewing the audit: retire N27 and raise the status")
    p.add_argument("--skip-tests", action="store_true", help="do not run the pytest suite first")
    p.add_argument("--quiet", action="store_true", help="only step headers on the console (full output stays in the logs)")
    p.add_argument("--processed-dir", default=os.getenv("CERT_PROCESSED_DIR"))
    p.add_argument("--models-dir", default=os.getenv("MODEL_PATH", str(REPO / "models" / "saved_models")))
    p.add_argument("--seed", type=int, default=int(os.getenv("CIRA_SEED", "42")))
    p.add_argument("--experiments-dir", default=str(REPO / "experiments"), help=argparse.SUPPRESS)   # tests
    p.add_argument("--docs-root", default=str(REPO), help=argparse.SUPPRESS)                        # tests
    p.add_argument("--skip-permutation", action="store_true", help=argparse.SUPPRESS)               # tests only
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    try:
        sys.stdout.reconfigure(errors="replace")     # a console that cannot show a character must not stop a run
    except (AttributeError, ValueError):
        pass
    args = parse_args(argv)
    ctx = Ctx(args)
    try:
        if args.finalize:
            return finalize(ctx)
        ctx.state["green"] = False
        ctx.state["started_at"] = now()
        ctx.save()
        tabnet = preflight(ctx)
        tests(ctx)
        runs = candidates(ctx, tabnet)
        verify_candidates(ctx, runs)
        decide(ctx, runs)
        test_readout(ctx)
        batch_run_id = batch(ctx)
        final_verify(ctx, runs, batch_run_id)
        health(ctx)
        audit = record(ctx, runs, batch_run_id)
    except SignoffError as exc:
        print(f"\nRED: {exc}\n\nFix it and run the same command again; finished steps are skipped.", file=sys.stderr)
        return 1
    ctx.state["green"] = True
    ctx.state["finished_at"] = now()
    ctx.save()
    warns = audit.read_text(encoding="utf-8").count(TO_EXPLAIN)
    served = read_json(ctx.decision)["outcome"]["served"]
    print(f"\nGREEN: Chapter 8 ran end to end with 0 FAIL. Serving {served['model_name']} {served['registry_version']}.")
    if warns:
        print(f"Next: open {audit} and replace the {warns} '{TO_EXPLAIN}' line(s) with the reason each WARN is acceptable,")
        print("then run: python ../scripts/signoff_chapter8.py --finalize")
    else:
        print("No WARNs. Read the audit, then run: python ../scripts/signoff_chapter8.py --finalize")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
