"""Run everything Chapter 9 needs on the real data, in order, and stop at the first failure.

Usage, from backend/ (the script loads the repository's .env for any variable
not already set):

    python ../scripts/signoff_chapter9.py              # run / resume the sign-off
    python ../scripts/signoff_chapter9.py --finalize   # after reviewing the audit: raise the status

Sign-off sequence (CARRY_FORWARD N38, docs/chapters/chapter_9_cri.md "How to run"):

    0  preflight   env, the Chapter 8 decision, a full Chapter 8 batch scored by
                   the served model (with shadow rows), features, LDAP, labels
    1  tests       the full pytest suite (skip with --skip-tests)
    2  calibrate   python -m app.cri.calibrate --profile full (label-free)
    3  batch       python -m app.cri.batch --profile full (label-free)
    4  verify      verify_chapter9.py --no-readout, 0 FAIL, before any label is read
    5  readout     python -m app.cri.evaluate --profile full (validation only, once)
    6  verify      verify_chapter9.py including the readout, 0 FAIL
    7  health      the FastAPI app starts and /health reports the CRI as loaded
    8  record      experiments/chapter9_reference_runs.json and an audit draft
                   (docs/audits/chapter_9_audit.md) written from the output files

Every step runs in its own process, one at a time (HCEA §16); its output is
kept in experiments/results/chapter9/signoff_logs/. Progress is kept in
experiments/results/chapter9/signoff_state.json, so a re-run skips what is
already done. Nothing that exists is overwritten: an existing calibration
pin for another model stops the run (replace it deliberately with
``calibrate --supersede``), and the validation readout is written once.

The served model is always the one in the Chapter 8 decision file:
CIRA_SERVED_MODEL is ignored here, as in the Chapter 8 sign-off.

The audit draft contains only numbers copied from the output files. Every
WARN becomes a "TO EXPLAIN" line; ``--finalize`` refuses while any remain.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
BACKEND = REPO / "backend"
TO_EXPLAIN = "TO EXPLAIN"
DRAFT_MARK = "<!-- generated by scripts/signoff_chapter9.py from run outputs -->"
STATUS_PENDING = "| 9 | Contextual Risk Intelligence (CRI), Asset entity | PARTIALLY IMPLEMENTED; synthetic tests pass, CERT runs pending (N38) |"
N38_HEADING = "## N38. Chapter 9 is PARTIALLY IMPLEMENTED until real runs exist  (from Chapter 9)\n\n"


class SignoffError(RuntimeError):
    """A step failed; the sign-off stops here."""


def now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def load_dotenv(path: Path) -> list[str]:
    loaded = []
    if not path.exists():
        return loaded
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key, value = key.strip(), value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value
            loaded.append(key)
    return loaded


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")
    tmp.replace(path)


def fmt(v, nd: int = 3) -> str:
    if v is None:
        return "n/a"
    return f"{v:.{nd}f}" if isinstance(v, float) else str(v)


def verifier_counts(output: str) -> dict:
    for line in reversed(output.splitlines()):
        if " PASS, " in line and " FAIL" in line and "[verify chapter9]" in line:
            parts = line.split("]", 1)[1].split("->")[0].replace(",", "").split()
            return {parts[i + 1]: int(parts[i]) for i in range(0, 6, 2)}
    return {}


def verifier_lines(output: str, status: str) -> list[str]:
    return [line.strip() for line in output.splitlines() if line.strip().startswith(status + " ")]


class Ctx:
    def __init__(self, args: argparse.Namespace) -> None:
        self.args = args
        exp = Path(args.experiments_dir)
        self.exp = exp
        self.results = exp / "results" / "chapter9"
        self.logs = self.results / "signoff_logs"
        self.state_path = self.results / "signoff_state.json"
        self.decision = exp / "chapter8_serving_decision.json"
        self.pin = exp / "chapter9_cri_calibration.json"
        self.readout = exp / "chapter9_validation_readout.json"
        self.reference = exp / "chapter9_reference_runs.json"
        self.docs = Path(args.docs_root)
        self.audit = self.docs / "docs" / "audits" / "chapter_9_audit.md"
        self.processed = Path(args.processed_dir) if args.processed_dir else None
        self.models = Path(args.models_dir)
        self.runlog = Path(os.environ.get("CIRA_RUNLOG", str(exp / "runlog.jsonl")))
        self.state = read_json(self.state_path) if self.state_path.exists() else {}

    def save(self) -> None:
        self.state["updated_at"] = now()
        write_json(self.state_path, self.state)

    def env(self) -> dict:
        env = dict(os.environ)
        env["MODEL_PATH"] = str(self.models)
        env["CIRA_SERVING_DECISION"] = str(self.decision)
        env["CIRA_CRI_CALIBRATION"] = str(self.pin)
        env["CERT_PROCESSED_DIR"] = str(self.processed)
        env["CIRA_RUNLOG"] = str(self.runlog)
        env.pop("CIRA_SERVED_MODEL", None)
        env.pop("CIRA_SHADOW_MODEL", None)
        env["PYTHONPATH"] = str(BACKEND) + os.pathsep + env.get("PYTHONPATH", "")
        env["PYTHONIOENCODING"] = "utf-8"
        return env

    def run(self, name: str, argv: list[str], *, cwd: Path = BACKEND) -> tuple[int, str]:
        self.logs.mkdir(parents=True, exist_ok=True)
        log = self.logs / f"{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}_{name}.log"
        print(f"\n>>> {name}: {' '.join(argv)}", flush=True)
        lines = []
        with log.open("w", encoding="utf-8") as fh:
            proc = subprocess.Popen([sys.executable, *argv], cwd=cwd, env=self.env(), stdout=subprocess.PIPE,
                                    stderr=subprocess.STDOUT, text=True, encoding="utf-8", errors="replace")
            for line in proc.stdout:
                fh.write(line)
                lines.append(line)
                if not self.args.quiet:
                    sys.stdout.write(line)
            code = proc.wait()
        print(f"<<< {name}: exit {code}  (log: {log})", flush=True)
        return code, "".join(lines)

    def common(self) -> list[str]:
        return ["--processed-dir", str(self.processed), "--profile", self.args.profile]


# ---------------------------------------------------------------------------
# steps
# ---------------------------------------------------------------------------

def preflight(ctx: Ctx) -> dict:
    print("=== 0 preflight ===")
    if ctx.processed is None:
        raise SignoffError("CERT_PROCESSED_DIR is not set (in .env or the environment)")
    if not ctx.decision.exists():
        raise SignoffError(f"{ctx.decision} not found; Chapter 8 must be signed off first")
    served = read_json(ctx.decision)["outcome"]["served"]
    root = ctx.processed / "scores" / "chapter8"
    batches = []
    for d in sorted(root.iterdir()) if root.exists() else []:
        meta = d / "batch_meta.json"
        if meta.exists():
            m = read_json(meta)
            if m.get("profile") == ctx.args.profile:
                batches.append((d.name, m))
    if not batches:
        raise SignoffError(f"no {ctx.args.profile} Chapter 8 batch under {root}; run `python -m app.scoring.batch "
                           f"--profile {ctx.args.profile} --with-shadow`")
    batch_id, bm = batches[-1]
    if (bm["served"]["model_name"], bm["served"]["registry_version"]) != (served["model_name"], served["registry_version"]):
        raise SignoffError(f"newest batch {batch_id} was scored by {bm['served']['model_name']}:"
                           f"{bm['served']['registry_version']}, the decision serves {served['model_name']}:"
                           f"{served['registry_version']}")
    if not bm.get("shadow"):
        print(f"  note: batch {batch_id} has no shadow rows; the served-vs-shadow report will be empty")
    needed = {
        "features": ctx.processed / "features" / f"user_day_{ctx.args.profile}.parquet",
        "LDAP context": ctx.processed / "context" / "ldap_user_month.parquet",
        "primary labels": ctx.processed / "labels" / "insider_user_days.parquet",
        "account labels": ctx.processed / "labels" / "account_user_days.parquet",
    }
    for what, path in needed.items():
        if not path.exists():
            raise SignoffError(f"{what} missing: {path}")
    if str(BACKEND) not in sys.path:
        sys.path.insert(0, str(BACKEND))
    from app.cri.config import CRIConfig, CRIConfigError   # stdlib only; no numpy

    try:
        overrides = dict(CRIConfig.from_env().overrides)
    except CRIConfigError as exc:
        raise SignoffError(f"CRI configuration in .env or the environment is invalid: {exc}")
    if overrides:
        raise SignoffError(
            "CRI_* values in .env or the environment differ from the Chapter 9 defaults, which were fixed before any "
            f"CRI number existed (N37): {overrides}. Replace the CRI block of .env with the one in .env.example "
            "(or delete those lines) and run again. A deliberate change of weights is a new configuration: change "
            "the defaults in backend/app/cri/config.py and say why in the chapter document")
    print(f"  served {served['model_name']} {served['registry_version']} ({served['model_version']}); "
          f"Chapter 8 batch {batch_id}")
    ctx.state["served"] = served
    ctx.state["chapter8_batch"] = batch_id
    ctx.save()
    return served


def tests(ctx: Ctx) -> None:
    print("\n=== 1 tests ===")
    if ctx.args.skip_tests:
        print("  skipped (--skip-tests)")
        return
    code, out = ctx.run("pytest", ["-m", "pytest", "-q"], cwd=REPO)
    if code != 0:
        raise SignoffError("the test suite failed; see the log")
    ctx.state["tests"] = next((l.strip() for l in reversed(out.splitlines()) if " passed" in l), "passed")
    ctx.save()


def calibrate(ctx: Ctx, served: dict) -> str:
    print("\n=== 2 calibrate ===")
    if ctx.pin.exists():
        cur = read_json(ctx.pin)["current"]
        if cur["model"].get("model_version") != served["model_version"]:
            raise SignoffError(
                f"{ctx.pin} pins calibration {cur['calibration_id']} for {cur['model'].get('model_version')}, but the "
                f"served model is {served['model_version']}. Replace it deliberately with `python -m app.cri.calibrate "
                "--supersede \"<reason>\"` (N29); the sign-off never supersedes on its own")
        if cur["source_batch_run_id"] != ctx.state["chapter8_batch"]:
            raise SignoffError(f"the pinned calibration was fitted on batch {cur['source_batch_run_id']}, the newest "
                               f"batch is {ctx.state['chapter8_batch']}; pass it explicitly or supersede the calibration")
        print(f"  calibration {cur['calibration_id']} already pinned for the served model; skipped")
        ctx.state["calibration_id"] = cur["calibration_id"]
        ctx.save()
        return cur["calibration_id"]
    extra = ["--min-reference-rows", str(ctx.args.min_reference_rows)] if ctx.args.min_reference_rows else []
    code, _ = ctx.run("calibrate", ["-m", "app.cri.calibrate", *ctx.common(), "--batch-run-id", ctx.state["chapter8_batch"],
                                    "--models-dir", str(ctx.models), "--pin-path", str(ctx.pin), *extra])
    if code != 0:
        raise SignoffError("calibration refused; see the log")
    cal_id = read_json(ctx.pin)["current"]["calibration_id"]
    ctx.state["calibration_id"] = cal_id
    ctx.save()
    return cal_id


def _risk_meta(ctx: Ctx, cri_run_id: str) -> dict:
    return read_json(ctx.processed / "risk" / "chapter9" / cri_run_id / "cri_meta.json")


def batch(ctx: Ctx, cal_id: str) -> str:
    print("\n=== 3 batch ===")
    rid = ctx.state.get("cri_run_id")
    if rid and (ctx.processed / "risk" / "chapter9" / rid / "cri_meta.json").exists():
        m = _risk_meta(ctx, rid)
        if m["calibration"]["calibration_id"] == cal_id and m.get("is_calibrated_default"):
            print(f"  risk run {rid} already made with calibration {cal_id}; skipped")
            return rid
    code, out = ctx.run("cri_batch", ["-m", "app.cri.batch", *ctx.common(), "--batch-run-id", ctx.state["chapter8_batch"],
                                      "--models-dir", str(ctx.models), "--pin-path", str(ctx.pin)])
    if code != 0:
        raise SignoffError("the CRI batch refused; see the log")
    line = next((l for l in out.splitlines() if l.startswith("[cri] ") and ": " in l and "-cri-" in l), "")
    rid = line.split("[cri] ", 1)[1].split(":", 1)[0].strip() if line else None
    if not rid:
        raise SignoffError("could not read the risk run id from the batch output")
    if not _risk_meta(ctx, rid).get("is_calibrated_default"):
        raise SignoffError(f"risk run {rid} is not the calibrated default configuration; check .env for CRI_* overrides")
    ctx.state["cri_run_id"] = rid
    ctx.save()
    return rid


def verify(ctx: Ctx, rid: str, *, with_readout: bool) -> dict:
    name = "verify_with_readout" if with_readout else "verify"
    print(f"\n=== {'6' if with_readout else '4'} {name} ===")
    argv = [str(REPO / "scripts" / "verify_chapter9.py"), *ctx.common(), "--cri-run-id", rid,
            "--pin-path", str(ctx.pin), "--models-dir", str(ctx.models), "--readout-path", str(ctx.readout),
            "--results-dir", str(ctx.results)]
    if not with_readout:
        argv.append("--no-readout")
    code, out = ctx.run(name, argv)
    counts = verifier_counts(out)
    if code != 0 or counts.get("FAIL", 1) != 0:
        raise SignoffError(f"verifier: {counts or 'no summary line'}; fix every FAIL first")
    record = {"counts": counts, "warn": verifier_lines(out, "WARN")}
    ctx.state[name] = record
    ctx.save()
    return record


def readout(ctx: Ctx, rid: str) -> dict:
    print("\n=== 5 readout ===")
    if ctx.readout.exists():
        r = read_json(ctx.readout)
        if r.get("cri_run_id") != rid:
            raise SignoffError(f"{ctx.readout} is for risk run {r.get('cri_run_id')}, not {rid}; the readout is written "
                               "once (N37). Supersede it deliberately with `python -m app.cri.evaluate --supersede`")
        print("  validation readout already written for this risk run; skipped")
        return r
    code, _ = ctx.run("readout", ["-m", "app.cri.evaluate", *ctx.common(), "--cri-run-id", rid,
                                  "--decision-path", str(ctx.decision), "--readout-path", str(ctx.readout),
                                  "--results-dir", str(ctx.results)])
    if code != 0:
        raise SignoffError("the validation readout refused; see the log")
    return read_json(ctx.readout)


def health(ctx: Ctx, cal_id: str) -> dict:
    print("\n=== 7 health ===")
    if ctx.args.skip_health:
        print("  skipped (--skip-health, tests only: the synthetic world has no registered model to load)")
        ctx.state["health"] = {"skipped": True}
        ctx.save()
        return {}
    probe = ("import json\nfrom fastapi.testclient import TestClient\nfrom app.main import app\n"
             "with TestClient(app) as c:\n    print('HEALTH ' + json.dumps(c.get('/health').json()))\n")
    code, out = ctx.run("health", ["-c", probe])
    line = next((l for l in out.splitlines() if l.startswith("HEALTH ")), None)
    if code != 0 or line is None:
        raise SignoffError("the API did not start; see the log")
    body = json.loads(line[len("HEALTH "):])
    cri = body.get("cri") or {}
    if cri.get("status") != "loaded" or (cri.get("calibration") or {}).get("calibration_id") != cal_id:
        raise SignoffError(f"/health does not report the CRI with calibration {cal_id}: {cri}")
    print(f"  /health: {body['status']}, CRI loaded with {cal_id}")
    ctx.state["health"] = {"status": body["status"], "cri": "loaded", "calibration_id": cal_id}
    ctx.save()
    return body


# ---------------------------------------------------------------------------
# record
# ---------------------------------------------------------------------------

def write_reference(ctx: Ctx, rid: str, cal_id: str) -> None:
    write_json(ctx.reference, {
        "description": ("Reported Chapter 9 runs (CARRY_FORWARD N38). Chapter 12 loads risk scores from this run; "
                        "Chapter 16's ablations C/D recombine its components. If anything is re-run for the record, "
                        "change it here and in docs/audits/chapter_9_audit.md."),
        "served": ctx.state["served"],
        "chapter8_batch_run_id": ctx.state["chapter8_batch"],
        "calibration_id": cal_id,
        "cri_run_id": rid,
        "validation_readout": ctx.readout.name,
        "recorded_at": now(),
    })


def _scenario(d: dict | None) -> str:
    return ", ".join(f"s{k} {v}" for k, v in (d or {}).items()) or "-"


def audit_text(ctx: Ctx, rid: str, cal_id: str) -> str:
    cal_meta = read_json(ctx.models / "cri" / cal_id / "calibration.json")
    risk = _risk_meta(ctx, rid)
    r = read_json(ctx.readout)
    rep, ref = cal_meta["report"], cal_meta["reference"]
    served = ctx.state["served"]
    out = [DRAFT_MARK, "", f"# Chapter 9 audit ({datetime.now(timezone.utc).strftime('%d %B %Y')})", "",
           "Scope: Chapter 9 (Contextual Risk Intelligence), checked against the Bible Chapter 9 acceptance",
           "list, HCEA v1.0 §9 and CARRY_FORWARD N1-N39.",
           "Evidence: `experiments/chapter9_cri_calibration.json`, `experiments/chapter9_validation_readout.json`,",
           "`experiments/chapter9_reference_runs.json`, `experiments/runlog.jsonl` and the verifier output (logs",
           "under `experiments/results/chapter9/signoff_logs/`, gitignored). Every number below is copied from those",
           "files by `scripts/signoff_chapter9.py`.", "",
           f"Served model: {served['model_name']} {served['registry_version']} (`{served['model_version']}`), "
           f"from the Chapter 8 decision. Calibration `{cal_id}`; risk run `{rid}`.", "",
           "## Verification record", "", "| What | Verifier |", "|---|---|"]
    for key, what in (("verify", "calibration + risk run, before labels"), ("verify_with_readout", "including the readout")):
        c = ctx.state.get(key, {}).get("counts", {})
        out.append(f"| {what} | {c.get('PASS')} PASS, {c.get('WARN')} WARN, {c.get('FAIL')} FAIL |")
    out.append(f"| test suite | {ctx.state.get('tests', 'skipped')} |")
    h = ctx.state.get("health", {})
    out.append(f"| /health | {'SKIPPED (tests-only flag; never acceptable for the real sign-off)' if h.get('skipped') else h.get('status', 'n/a') + ', CRI ' + str(h.get('cri'))} |")
    out += ["", "WARNs and why they are acceptable:", ""]
    warns = sorted(set(ctx.state.get("verify", {}).get("warn", []) + ctx.state.get("verify_with_readout", {}).get("warn", [])))
    out += [f"- `{w}`: {TO_EXPLAIN}" for w in warns] or ["- none."]
    out += ["", "## Calibration (label-free)", "",
            f"Reference: {ref['rows']} validation user-days ({ref['users']} users, {ref['days']} days) of Chapter 8 batch "
            f"`{cal_meta['source_batch']['batch_run_id']}`. Maximum reachable rarity {fmt(ref['max_reachable_rarity'])} "
            f"(D = {cal_meta['rarity_decades']}).", "",
            "| model_split | rows | q0.5 | q0.9 | q0.99 | q0.999 | max |", "|---|---|---|---|---|---|---|"]
    for split, q in rep["served_score_quantiles_by_model_split"].items():
        out.append(f"| {split} | {q.get('rows')} | " + " | ".join(f"{q.get(k, float('nan')):.3g}" for k in ("0.5", "0.9", "0.99", "0.999", "max")) + " |")
    ctx_rep = rep["context_on_reference"]
    out += ["", f"Context on the reference: historical null share {fmt(ctx_rep['historical_null_share'])}, peer null share "
            f"{fmt(ctx_rep['peer_null_share'])}, no LDAP row {fmt(ctx_rep['user_context_null_share'])}, privileged user-days "
            f"{fmt(ctx_rep['privileged_user_day_share'], 4)} ({ctx_rep['privileged_users']} users).", ""]
    sv = rep.get("served_vs_shadow")
    if sv:
        out += ["### Served vs shadow on the same validation user-days (N32 monitoring)", "",
                f"Shadow {sv['shadow_model']}, {sv['rows']} rows. Spearman {fmt(sv['spearman_rank_correlation'])}; "
                f"top-1% overlap {fmt(sv['top_1pct_overlap'])}; share of shadow scores at or above the served model's "
                f"99th percentile {fmt(sv['share_of_shadow_at_or_above_served_q99'], 4)}, and the reverse "
                f"{fmt(sv['share_of_served_at_or_above_shadow_q99'], 4)}; mean daily top-1 Jaccard "
                f"{fmt(sv['daily_top_k_agreement']['1']['mean_jaccard'])}, top-5 {fmt(sv['daily_top_k_agreement']['5']['mean_jaccard'])}.", ""]
    s = risk["summary"]
    out += ["## Risk run (label-free)", "",
            f"{s['rows']} user-days. Severity: " + ", ".join(f"{k} {v}" for k, v in s["severity"].items()) + ".",
            f"Effective weights: " + ", ".join(f"{k} {v:.3f}" for k, v in risk["effective_weights"].items()) + ".",
            "Unavailable: " + "; ".join(f"{k} ({v})" for k, v in risk["unavailable_components"].items()) + ".", ""]
    for split, vol in s["daily_volume_out_of_sample"].items():
        h, c = vol["HIGH_or_above"], vol["CRITICAL"]
        out.append(f"- {split}: HIGH or above per day median {h.get('median')}, p95 {h.get('p95')}, max {h.get('max')}; "
                   f"CRITICAL per day median {c.get('median')}, max {c.get('max')}")
    out += ["", f"## Validation readout ({r['rows']} rows, {r['positives']} malicious user-days, chance {fmt(r['chance_pr_auc'], 4)})", "",
            "| Ranking | PR-AUC | ROC-AUC (secondary) | Recall@1 | Caught@1 | Caught@5 | Days at top-1 by scenario | Insiders at top-1 by scenario |",
            "|---|---|---|---|---|---|---|---|"]
    for name, m in r["models"].items():
        out.append(f"| {name} | {fmt(m['pr_auc'])} | {fmt(m['roc_auc_secondary'])} | {fmt(m['recall_at_1'])} | "
                   f"{m['insiders_caught_at_1']} | {m['insiders_caught_at_5']} | {_scenario(m['days_by_scenario_at_1'])} | "
                   f"{_scenario(m['caught_by_scenario_at_1'])} |")
    for name, m in (r.get("chapter8_reference_rows") or {}).items():
        out.append(f"| {name} anomaly score (Ch8 evidence, not a CRI) | {fmt(m['pr_auc'])} | | | {m['insiders_caught_at_1']} | | "
                   f"{_scenario(m['recall_by_scenario_at_1'])} | {_scenario(m['caught_by_scenario_at_1'])} |")
    b = r["bands"]["cri:default"]
    out += ["", "Default CRI as a band alert (primary view):", ""]
    for band in ("HIGH_or_above", "CRITICAL"):
        x = b[band]
        out.append(f"- {band}: {x['alerts']} alerts, precision {fmt(x['precision'])}, recall {fmt(x['recall'])}, insiders "
                   f"caught {x['per_user']['caught']}/{x['per_user']['insiders']}, alerts per day median "
                   f"{x['alerts_per_day'].get('median')}, max {x['alerts_per_day'].get('max')}")
    out += ["", f"Harness: " + "; ".join(f"{h['check']}: {'PASS' if h['ok'] else ('n/a' if h['ok'] is None else 'FAIL')}"
                                        for h in r["harness"]) + ".", "",
            f"Guard {r['guard']['version']}: " + ("no warning." if not r["guard"]["warnings"] else
                                                  f"{len(r['guard']['warnings'])} warning(s), listed with the WARNs above."),
            "", "## Notes", "",
            "- One seed per model; no confidence intervals yet. Chapter 16 adds seeds and bootstrap intervals (C6-2, C7-7).",
            "- The CRI was not read on test. Its test readout is Chapter 16's ablation C (N37).",
            "- Any scenario-3 difference from user_context is expected by construction and is not evidence (N36).",
            "- Rows tagged `train` are in-sample; nothing above quotes detection from them (N31).", ""]
    return "\n".join(out)


def record(ctx: Ctx, rid: str, cal_id: str) -> Path:
    print("\n=== 8 record ===")
    write_reference(ctx, rid, cal_id)
    text = audit_text(ctx, rid, cal_id)
    target = ctx.audit
    if target.exists() and DRAFT_MARK not in target.read_text(encoding="utf-8"):
        target = target.with_name("chapter_9_audit.generated.md")
        print(f"  {ctx.audit} was edited by hand; the fresh draft goes to {target} instead")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")
    print(f"  written: {target}")
    return target


# ---------------------------------------------------------------------------
# finalize
# ---------------------------------------------------------------------------

def _replace(path: Path, old: str, new: str, what: str, manual: list[str]) -> None:
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    if new in text:
        return
    if old not in text:
        manual.append(f"{path}: {what}")
        return
    path.write_text(text.replace(old, new, 1), encoding="utf-8")
    print(f"  updated {path}: {what}")


def finalize(ctx: Ctx) -> int:
    st = ctx.state
    if not st.get("green"):
        raise SignoffError("the last sign-off run was not green; run the sign-off first")
    if not ctx.audit.exists():
        raise SignoffError(f"{ctx.audit} does not exist")
    text = ctx.audit.read_text(encoding="utf-8")
    if TO_EXPLAIN in text:
        raise SignoffError(f"{ctx.audit} still has {text.count(TO_EXPLAIN)} '{TO_EXPLAIN}' line(s); explain every WARN first (N38)")
    if DRAFT_MARK in text:
        ctx.audit.write_text(text.replace(DRAFT_MARK + "\n\n", "").replace(DRAFT_MARK, ""), encoding="utf-8")
    served, cal_id = st["served"], st["calibration_id"]
    stamp = datetime.now(timezone.utc).strftime("%d %B %Y")
    manual: list[str] = []
    cf = ctx.docs / "docs" / "CARRY_FORWARD.md"
    _replace(cf, "| N38 Chapter 9 status | 9 (until retired) |", "| N38 Chapter 9 status (RETIRED) | - |", "N38 row retired", manual)
    _replace(cf, N38_HEADING, N38_HEADING + "RETIRED (chapter 9, runs verified; see `docs/audits/chapter_9_audit.md`).\n\n",
             "N38 marked RETIRED", manual)
    readme = ctx.docs / "README.md"
    _replace(readme, STATUS_PENDING,
             f"| 9 | Contextual Risk Intelligence (CRI), Asset entity | IMPLEMENTED; calibrated for {served['model_name']} "
             f"{served['registry_version']} |", "status row", manual)
    chap = ctx.docs / "docs" / "chapters" / "chapter_9_cri.md"
    chap_text = chap.read_text(encoding="utf-8") if chap.exists() else ""
    start = chap_text.find("Status: PARTIALLY IMPLEMENTED")
    end = chap_text.find("\n\n", start)
    if start >= 0 and end > start:
        chap_text = chap_text[:start] + (
            f"Status: IMPLEMENTED ({stamp}). Verified on CERT r4.2 with 0 FAIL; the runs, the validation\n"
            f"readout and every WARN are in `docs/audits/chapter_9_audit.md`. Calibration `{cal_id}` for\n"
            f"{served['model_name']} {served['registry_version']} (`{served['model_version']}`). Reported runs:\n"
            "`experiments/chapter9_reference_runs.json`."
        ) + chap_text[end:]
        section = chap_text.find("Real runs (N38), not yet done:")
        if section >= 0:
            chap_text = chap_text[:section] + chap_text[section:].replace("Real runs (N38), not yet done:", "Real runs (N38):", 1).replace("- [ ] ", "- [x] ")
        chap.write_text(chap_text, encoding="utf-8")
        print(f"  updated {chap}: status IMPLEMENTED, real-run checklist ticked")
    elif "Status: IMPLEMENTED" not in chap_text:
        manual.append(f"{chap}: set the status line to IMPLEMENTED")
    st["finalized_at"] = now()
    ctx.save()
    if manual:
        print("\nEdit these by hand (their text no longer matched):\n  " + "\n  ".join(manual))
    print("\nChapter 9 is signed off. Commit:\n"
          "  git add experiments/chapter9_cri_calibration.json experiments/chapter9_validation_readout.json "
          "experiments/chapter9_reference_runs.json experiments/runlog.jsonl docs/ README.md\n"
          "  git commit -m \"Chapter 9 sign-off: CRI calibration, risk batch, validation readout, audit\"")
    return 0


def parse_args(argv: list[str] | None) -> argparse.Namespace:
    pre = argparse.ArgumentParser(add_help=False)
    pre.add_argument("--dotenv", default=str(REPO / ".env"))
    load_dotenv(Path(pre.parse_known_args(argv)[0].dotenv))
    p = argparse.ArgumentParser(description="CIRA Chapter 9 sign-off")
    p.add_argument("--dotenv", default=str(REPO / ".env"), help=argparse.SUPPRESS)                   # tests
    p.add_argument("--finalize", action="store_true", help="after reviewing the audit: retire N38 and raise the status")
    p.add_argument("--skip-tests", action="store_true")
    p.add_argument("--quiet", action="store_true")
    p.add_argument("--processed-dir", default=os.getenv("CERT_PROCESSED_DIR"))
    p.add_argument("--models-dir", default=os.getenv("MODEL_PATH", str(REPO / "models" / "saved_models")))
    p.add_argument("--profile", default="full", help=argparse.SUPPRESS)                              # tests only
    p.add_argument("--experiments-dir", default=str(REPO / "experiments"), help=argparse.SUPPRESS)   # tests
    p.add_argument("--docs-root", default=str(REPO), help=argparse.SUPPRESS)                        # tests
    p.add_argument("--skip-health", action="store_true", help=argparse.SUPPRESS)                    # tests only
    p.add_argument("--min-reference-rows", type=int, default=None, help=argparse.SUPPRESS)          # tests only
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    try:
        sys.stdout.reconfigure(errors="replace")
    except (AttributeError, ValueError):
        pass
    args = parse_args(argv)
    ctx = Ctx(args)
    try:
        if args.finalize:
            return finalize(ctx)
        ctx.state["green"] = False
        ctx.state["started_at"] = now()
        ctx.save()
        served = preflight(ctx)
        tests(ctx)
        cal_id = calibrate(ctx, served)
        rid = batch(ctx, cal_id)
        verify(ctx, rid, with_readout=False)
        readout(ctx, rid)
        verify(ctx, rid, with_readout=True)
        health(ctx, cal_id)
        audit = record(ctx, rid, cal_id)
    except SignoffError as exc:
        print(f"\nRED: {exc}\n\nFix it and run the same command again; finished steps are skipped.", file=sys.stderr)
        return 1
    ctx.state["green"] = True
    ctx.state["finished_at"] = now()
    ctx.save()
    warns = audit.read_text(encoding="utf-8").count(TO_EXPLAIN)
    print("\nGREEN: Chapter 9 ran end to end with 0 FAIL.")
    if warns:
        print(f"Next: open {audit} and replace the {warns} '{TO_EXPLAIN}' line(s) with the reason each WARN is acceptable,")
        print("then run: python ../scripts/signoff_chapter9.py --finalize")
    else:
        print("No WARNs. Read the audit, then run: python ../scripts/signoff_chapter9.py --finalize")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
